export interface RouteServiceOptions {
  centerKey?: boolean | string;
  zoomKey?: boolean | string;
  projectionKey?: boolean | string;
  contextKey?: boolean | string;
  searchKey?: boolean | string;
  visibleOnLayersKey?: boolean | string;
  visibleOffLayersKey?: boolean | string;
  directionsCoordKey?: boolean | string;
  directionsOptionsKey?: boolean | string;
  toolKey?: boolean | string;
  wmsUrlKey?: boolean | string;
  wmsLayersKey?: boolean | string;
  wmtsUrlKey?: boolean | string;
  wmtsLayersKey?: boolean | string;
  arcgisUrlKey?: boolean | string;
  arcgisLayersKey?: boolean | string;
  iarcgisUrlKey?: boolean | string;
  iarcgisLayersKey?: boolean | string;
  tarcgisUrlKey?: boolean | string;
  tarcgisLayersKey?: boolean | string;
  vectorKey?: boolean | string;
}
