name: Deploy demo content to Pages

on:
  workflow_call:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: npm ci
      - name: Build librairies
        run: npm run build.libs
      - name: Build demo
        run: npm run build.ghpages -w demo -- --base-href /${{ github.event.repository.name }}/
      - name: SPA routing
        run: cp ./dist/ghpages/browser/index.html ./dist/ghpages/browser/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/ghpages/browser'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
