# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 

name: push

on:
  workflow_dispatch:
  push:
    branches-ignore: 
      - master
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: The branch or tag ref that triggered the workflow run.
      run: echo ${GITHUB_REF#refs/*/}

    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
  
    - name: Install dependencies
      run: npm ci
    
    - name: Check Quality
      run: npm run circular-deps.check & npm run lint

    - name: Test
      run: npm run e2e & npm run test
    
    - name: Build
      run: npm run build.libs
